# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stomp}
  s.version = "1.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian McCallister", "Marius Mathiesen", "Thiago Morello"]
  s.date = %q{2010-03-01}
  s.description = %q{Ruby client for the Stomp messaging protocol}
  s.email = ["brianm@apache.org", "marius@stones.com", "morellon@gmail.com"]
  s.executables = ["catstomp", "stompcat"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.rdoc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "bin/catstomp",
     "bin/stompcat",
     "examples/consumer.rb",
     "examples/publisher.rb",
     "lib/stomp.rb",
     "lib/stomp/client.rb",
     "lib/stomp/connection.rb",
     "lib/stomp/errors.rb",
     "lib/stomp/ext/hash.rb",
     "lib/stomp/message.rb",
     "lib/stomp/version.rb",
     "spec/client_shared_examples.rb",
     "spec/client_spec.rb",
     "spec/connection_spec.rb",
     "spec/message_spec.rb",
     "spec/spec_helper.rb",
     "stomp.gemspec",
     "test/test_client.rb",
     "test/test_connection.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://stomp.codehaus.org/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby client for the Stomp messaging protocol}
  s.test_files = [
    "spec/client_shared_examples.rb",
     "spec/client_spec.rb",
     "spec/connection_spec.rb",
     "spec/message_spec.rb",
     "spec/spec_helper.rb",
     "test/test_client.rb",
     "test/test_connection.rb",
     "test/test_helper.rb",
     "examples/consumer.rb",
     "examples/publisher.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

